src/Entity/Biography.php
<?php

namespace App\Entity;

use App\Service\GenericFunction;
use Doctrine\ORM\Mapping as ORM;

use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Metadata\ApiProperty;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BiographyRepository")
 */
#[ApiResource(
    operations: [
        new Get(security: "is_granted('ROLE_ADMIN')"),
        new GetCollection(security: "is_granted('ROLE_ADMIN')")
    ],
    normalizationContext: ['groups' => ['read']],
    denormalizationContext: ['groups' => ['write']]
)]
class Biography
{
	const AUTHOR = "author";
	const FICTIONAL_CHARACTER = "fictionalCharacter";
	
	const AUTHOR_CANONICAL = "biography.type.Author";
	const FICTIONAL_CHARACTER_CANONICAL = "biography.type.FictionalCharacter";

	const FOLDER = "biography";
	const PATH_FILE = "photo/".self::FOLDER."/";

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * #[ApiProperty(identifier: false)]
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"read", "write"})
     */
    protected $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups({"read", "write"})
     */
    protected $text;
	
    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"read", "write"})
     */
    protected $dayBirth;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"read", "write"})
     */
    protected $monthBirth;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"read", "write"})
     */
    protected $yearBirth;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"read", "write"})
     */
    protected $dayDeath;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"read", "write"})
     */
    protected $monthDeath;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"read", "write"})
     */
    protected $yearDeath;

	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\Country")
     * @Groups({"read", "write"})
     */
    protected $country;
	
	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\Language")
     * @Groups({"read", "write"})
     */
	protected $language;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $type;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Source", mappedBy="authors")
     */
    private $sources;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Source", mappedBy="fictionalCharacters")
     */
    private $artworks;
	
	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\FileManagement", cascade={"persist"})
     * @Groups({"read", "write"})
     */
    protected $fileManagement;

	/**
	 * @var string $wikidata
	 *
	 * @ORM\Column(name="wikidata", type="string", length=15, nullable=true)
     * @Groups({"read", "write"})
     * #[ApiProperty(identifier: true)]
	 */
	private $wikidata;
	
	public function getTypeCanonical()
	{
		switch($this->type)
		{
			case self::AUTHOR:
				return self::AUTHOR_CANONICAL;
			case self::FICTIONAL_CHARACTER:
				return self::FICTIONAL_CHARACTER_CANONICAL;
		}
		
		return null;
	}
	
	public function isFictionalCharacter()
	{
		return $this->type == self::FICTIONAL_CHARACTER;
	}
	
	public function isAuthor()
	{
		return $this->type == self::AUTHOR;
	}

	public function __toString()
	{
		return $this->title;
	}

	public function __construct()
	{
		$this->type = self::AUTHOR;
	}

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
		$this->setSlug();
    }

    public function getSlug()
    {
        return $this->slug;
    }

    public function setSlug()
    {
		if(empty($this->slug))
			$this->slug = GenericFunction::slugify($this->title);
    }

    public function getText()
    {
        return $this->text;
    }

    public function setText($text)
    {
        $this->text = $text;
    }

    public function getDayBirth()
    {
        return $this->dayBirth;
    }

    public function setDayBirth($dayBirth)
    {
        $this->dayBirth = $dayBirth;
    }

    public function getMonthBirth()
    {
        return $this->monthBirth;
    }

    public function setMonthBirth($monthBirth)
    {
        $this->monthBirth = $monthBirth;
    }

    public function getYearBirth()
    {
        return $this->yearBirth;
    }

    public function setYearBirth($yearBirth)
    {
        $this->yearBirth = $yearBirth;
    }

    public function getDayDeath()
    {
        return $this->dayDeath;
    }

    public function setDayDeath($dayDeath)
    {
        $this->dayDeath = $dayDeath;
    }

    public function getMonthDeath()
    {
        return $this->monthDeath;
    }

    public function setMonthDeath($monthDeath)
    {
        $this->monthDeath = $monthDeath;
    }

    public function getYearDeath()
    {
        return $this->yearDeath;
    }

    public function setYearDeath($yearDeath)
    {
        $this->yearDeath = $yearDeath;
    }

    public function getCountry()
    {
        return $this->country;
    }

    public function setCountry($country)
    {
        $this->country = $country;
    }
	
	public function getLanguage()
	{
		return $this->language;
	}
	
	public function setLanguage($language)
	{
		$this->language = $language;
	}
	
	public function getType()
	{
		return $this->type;
	}
	
	public function setType($type)
	{
		$this->type = $type;
	}
	
	public function getFileManagement()
	{
		return $this->fileManagement;
	}
	
	public function setFileManagement($fileManagement)
	{
		$this->fileManagement = $fileManagement;
	}

    /**
     * Set wikidata
     *
     * @param String $wikidata
     */
    public function setWikidata($wikidata)
    {
        $this->wikidata = $wikidata;
    }

    /**
     * Get wikidata
     *
     * @return String
     */
    public function getWikidata()
    {
        return $this->wikidata;
    }

    public function setSources($sources)
    {
        $this->sources = $sources;
    }

	public function removeSource($source)
	{
		$this->sources->removeElement($source);
	}

	public function getSources()
	{
		return $this->sources;
	}

	public function addSource($source)
	{
		$this->sources[] = $source;
	}

    public function setArtworks($artworks)
    {
        $this->artworks = $artworks;
    }

	public function removeArtwork($artwork)
	{
		$this->artworks->removeElement($artwork);
	}

	public function getArtworks()
	{
		return $this->artworks;
	}

	public function addArtwork($artwork)
	{
		$this->artworks[] = $artwork;
	}
}

src/Form/Type/BiographyType.php
<?php

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Repository\CountryRepository;
use App\Repository\LanguageRepository;

use App\Entity\Country;
use App\Entity\Language;
use App\Entity\Biography;

class BiographyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
		$locale = $options["locale"];

        $builder
            ->add('title', TextType::class, array(
                'constraints' => new Assert\NotBlank(), "label" => "admin.biography.Title"
            ))
			->add('text', TextareaType::class, array(
                'required' => false, "label" => "admin.biography.Text", 'attr' => array('class' => 'redactor')
            ))
			->add('fileManagement', FileManagementSelectorType::class, ["label" => "admin.biography.Image", "required" => false, "folder" => Biography::FOLDER])
			->add('dayBirth', IntegerType::class, array("label" => "admin.biography.BirthDate", "required" => false))
			->add('monthBirth', IntegerType::class, array("label" => "", "required" => false))
			->add('yearBirth', IntegerType::class, array("label" => "", "required" => false))
			->add('dayDeath', IntegerType::class, array("label" => "admin.biography.DeathDate", "required" => false))
			->add('monthDeath', IntegerType::class, array("label" => "", "required" => false))
			->add('yearDeath', IntegerType::class, array("label" => "", "required" => false))
			->add('wikidata', TextType::class, ['required' => false])
			->add('country', EntityType::class, array(
				'label' => 'admin.biography.Country',
				'class' => Country::class,
				'query_builder' => function (CountryRepository $er) use ($locale) {
					return $er->findAllForChoice($locale);
				},
				'multiple' => false, 
				'expanded' => false,
				'constraints' => array(new Assert\NotBlank()),
				'placeholder' => 'main.field.ChooseAnOption'
			))
			->add('language', EntityType::class, array(
				'label' => 'admin.form.Language', 
				'class' => Language::class,
				'query_builder' => function (LanguageRepository $er) use ($locale) {
					return $er->findAllForChoice($locale);
				},
				'multiple' => false,
				'required' => false,
				'expanded' => false,
				'placeholder' => 'main.field.ChooseAnOption'
			))
			->add('type', ChoiceType::class, [
				'label' => 'admin.biography.Type',
				'required' => true,
				'choices'  => [
					Biography::AUTHOR_CANONICAL => Biography::AUTHOR,
					Biography::FICTIONAL_CHARACTER_CANONICAL => Biography::FICTIONAL_CHARACTER
				],
			])
            ->add('save', SubmitType::class, array('label' => 'admin.main.Save', 'attr' => array('class' => 'btn btn-success')))
			;
    }

	/**
	 * {@inheritdoc}
	 */
	public function configureOptions(OptionsResolver $resolver)
	{
		$resolver->setDefaults(array(
			"data_class" => Biography::class,
			"locale" => null
		));
	}
	
    public function getName()
    {
        return 'biography';
    }
}

templates/Biography/_form.html.twig
{% import "Index/macro.html.twig" as macro %}

<div class="form-group row">
	{{ form_label(form.title, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
	<div class="col-sm-10">
		{{ form_errors(form.title) }}{{ form_widget(form.title, {'attr':{'class':'form-control'}}) }}
	</div>
</div>

<div class="form-group row">
	{{ form_label(form.text, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
	<div class="col-sm-10">
		{{ form_errors(form.text) }}{{ form_widget(form.text) }}
	</div>
</div>

<div class="form-group row">
	{{ form_label(form.dayBirth, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
	<div class="col-sm-10">
		{{ form_errors(form.dayBirth) }}
		<div class="input-group">
			{{ form_widget(form.dayBirth, {'attr':{'class':'day form-control'}}) }}
			<div class="input-group-append input-group-prepend"><span class="input-group-text">/</span></div>
			{{ form_widget(form.monthBirth, {'attr':{'class':'month form-control'}}) }}
			<div class="input-group-append input-group-prepend"><span class="input-group-text">/</span></div>
			{{ form_widget(form.yearBirth, {'attr':{'class':'year form-control'}}) }}
		</div>
	</div>
</div>

<div class="form-group row">
	{{ form_label(form.dayDeath, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
	<div class="col-sm-10">
		{{ form_errors(form.dayDeath) }}
		<div class="input-group">
			{{ form_widget(form.dayDeath, {'attr':{'class':'day form-control'}}) }}
			<div class="input-group-append input-group-prepend"><span class="input-group-text">/</span></div>
			{{ form_widget(form.monthDeath, {'attr':{'class':'month form-control'}}) }}
			<div class="input-group-append input-group-prepend"><span class="input-group-text">/</span></div>
			{{ form_widget(form.yearDeath, {'attr':{'class':'year form-control'}}) }}
		</div>
	</div>
</div>

<div class="form-group row">
	{{ form_label(form.fileManagement, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
	<div class="col-sm-10">
		{{ form_row(form.fileManagement) }}
	</div>
</div>

<div class="form-group row">
	{{ form_label(form.type, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
	<div class="col-sm-10">
		{{ form_errors(form.type) }}{{ form_widget(form.type, {'attr':{'class':'form-control'}}) }}
	</div>
</div>

<div class="form-group row">
	{{ form_label(form.language, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
	<div class="col-sm-10">
		{{ form_errors(form.language) }}{{ form_widget(form.language, {'attr':{'class':'form-control'}}) }}
	</div>
</div>

<div class="form-group row">
	{{ form_label(form.country, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
	<div class="col-sm-10">
		{{ form_errors(form.country) }}{{ form_widget(form.country, {'attr':{'class':'form-control'}}) }}
	</div>
</div>

<div class="form-group row">
	{{ form_label(form.wikidata, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
	<div class="col-sm-10">
		{{ form_errors(form.wikidata) }}{{ form_widget(form.wikidata, {'attr':{'class':'form-control'}}) }}
	</div>
</div>

<hr />
{{ form_widget(form.save, {'icon': 'fa-save'}) }}
{{ form_rest(form) }}

templates/Biography/edit.html.twig
{% extends sub_domain()~'_layout.html.twig' %}

{% block head_title %}{{ 'menu.left.Admin'|trans }} - {{ 'admin.index.Biography'|trans }}{% endblock %}
{% block main_title %}{{ 'menu.left.Admin'|trans }} - {{ 'admin.index.Biography'|trans }}{% endblock %}

{% block script_additional %}
	{% import "Index/macro.html.twig" as macro %}
	{{ macro.redactor() }}
	<script type="text/javascript">
		$(function()
		{
			$("select#{{ form.language.vars.id }}").change(function() {
				$.ajax({
					type: "GET",
					url: "{{ path('app_countryadmin_countries') }}",
					data: { "locale" : $(this).val() },
					success: function(data)
					{
						$("select#{{ form.country.vars.id }}").empty();
						$("select#{{ form.country.vars.id }}").append('<option value="" selected="selected">{{ 'main.field.ChooseAnOption'|trans }}</option>');
						
						for (var i = 0; i < data.length; i++) {
							$("select#{{ form.country.vars.id }}").append('<option value="'+ data[i].id +'">'+ data[i].name +'</option>');
						}
					}
				});
			});
		});
	</script>
{% endblock %}

{% block main_content %}
{% form_theme form 'Form/fields.html.twig' %}
{{ form_start(form, {'method' : 'post', 'action' : path('app_biographyadmin_update', {'id' : entity.id }), 'attr': {'novalidate': 'novalidate'} }) }}
	{% include "Biography/_form.html.twig" with {'form' : form} %}
{{ form_end(form) }}

{% endblock %}

templates/Biography/index.html.twig
{% extends sub_domain()~'_layout.html.twig' %}

{% block head_title %}{{ 'menu.left.Admin'|trans }} - {{ 'admin.index.Biography'|trans }}{% endblock %}
{% block main_title %}{{ 'menu.left.Admin'|trans }} - {{ 'admin.index.Biography'|trans }}{% endblock %}

{% block style_additional %}
	<link rel="stylesheet" type="text/css" href="{{ asset('js/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css') }}" media="screen" />
	<link rel="stylesheet" type="text/css" href="{{ asset('js/DataTables/Responsive-2.2.2/css/responsive.bootstrap.min.css') }}" media="screen" />
{% endblock %}
{% block script_additional %}
	<script src="{{ asset('js/DataTables/datatables.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/Responsive-2.2.2/js/dataTables.responsive.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/Responsive-2.2.2/js/responsive.bootstrap.min.js') }}"></script>

	<script type="text/javascript">
		$(function ()
		{
			var oTable = $('table.index_directories').DataTable({
				"oLanguage": {
					"sUrl": "{{ asset('js/DataTables/language/dataTables.'~app.request.locale) }}.txt"
				}, 
				"bFilter": true,
				"bInfo": true,
				"bSort": true,
				"bLengthChange": true,
				"iDisplayLength": 15,
				"bProcessing": true,
				"bServerSide": true,
				"sAjaxSource": "{{ path('app_biographyadmin_indexdatatables') }}",
				"autoWidth": false
			});

			$("select#selected_state").change(function()
			{
				oTable.ajax.url("{{ path('app_biographyadmin_indexdatatables') }}?state=" + $(this).val()).load();
			});
		});
	</script>
{% endblock %}

{% block main_content %}
	<label>{{ "admin.index.State"|trans }}</label>
	<select id="selected_state" class="form-control">
		<option value="all">{{ "admin.index.All"|trans }}</option>
		<option value="toComplete">{{ "admin.index.ToComplete"|trans }}</option>

	</select>
	<hr>
	<table class="index_directories table table-striped table-bordered dt-responsive">
		<thead>
			<th>Id</th>
			<th>{{ 'admin.table.Title'|trans }}</th>
			<th>{{ 'admin.form.Language'|trans }}</th>
			<th>{{ 'admin.table.Action'|trans }}</th>
		</thead>
		<tbody>
		</tbody>
	</table>
	<hr>
	<a href="{{ path('app_biographyadmin_new') }}"><i class="fas fa-plus-square"></i> {{ 'admin.index.Create'|trans }}</a>
{% endblock %}

templates/Biography/new.html.twig
{% extends sub_domain()~'_layout.html.twig' %}

{% block head_title %}{{ 'menu.left.Admin'|trans }} - {{ 'admin.index.Biography'|trans }}{% endblock %}
{% block main_title %}{{ 'menu.left.Admin'|trans }} - {{ 'admin.index.Biography'|trans }}{% endblock %}

{% block script_additional %}
	{% import "Index/macro.html.twig" as macro %}
	{{ macro.redactor() }}
	<script type="text/javascript">
		$(function()
		{
			$("select#{{ form.language.vars.id }}").change(function() {
				$.ajax({
					type: "GET",
					url: "{{ path('app_countryadmin_countries') }}",
					data: { "locale" : $(this).val() },
					success: function(data)
					{
						$("select#{{ form.country.vars.id }}").empty();
						$("select#{{ form.country.vars.id }}").append('<option value="" selected="selected">{{ 'main.field.ChooseAnOption'|trans }}</option>');
						
						for (var i = 0; i < data.length; i++) {
							$("select#{{ form.country.vars.id }}").append('<option value="'+ data[i].id +'">'+ data[i].name +'</option>');
							console.log(data[i]);
						}
					}
				});
			});
		});
	</script>
{% endblock %}

{% block main_content %}
{% form_theme form 'Form/fields.html.twig' %}
{{ form_start(form, {'method' : 'post', 'action' : path('app_biographyadmin_create'), 'attr': {'novalidate': 'novalidate'} }) }}
	{% include "Biography/_form.html.twig" with {'form' : form} %}
{{ form_end(form) }}

{% endblock %}

templates/Biography/show.html.twig
{% extends sub_domain()~'_layout.html.twig' %}

{% block head_title %}{{ 'menu.left.Admin'|trans }} - {{ 'admin.index.Biography'|trans }}{% endblock %}
{% block main_title %}{{ 'menu.left.Admin'|trans }} - {{ 'admin.index.Biography'|trans }}{% endblock %}

{% block main_content %}
	<table class="table table-bordered admin_show">
		<tr>
			<th>{{ 'admin.biography.Title'|trans }}</th>
			<td>{{ entity.title }}</td>
		</tr>
		<tr>
			<th>{{ 'admin.biography.Text'|trans }}</th>
			<td>{{ entity.text|raw }}</td>
		</tr>
		<tr>
			<th>{{ 'admin.biography.BirthDate'|trans }}</th>
			<td>{{ entity.dayBirth }}/{{ entity.monthBirth }}/{{ entity.yearBirth }}</td>
		</tr>
		<tr>
			<th>{{ 'admin.biography.DeathDate'|trans }}</th>
			<td>{{ entity.dayDeath }}/{{ entity.monthDeath }}/{{ entity.yearDeath }}</td>
		</tr>
		<tr>
			<th>{{ 'admin.biography.Image'|trans }}</th>
			<td>{% if entity.fileManagement is not empty %}<p class="text-center">{{ (constant('\\App\\Entity\\Biography::PATH_FILE')~entity.fileManagement.photo)|max_size_image() }}</p>{% endif %}</td>
		</tr>
		<tr>
			<th>{{ 'admin.biography.Type'|trans }}</th>
			<td>{{ entity.typeCanonical|trans }}</td>
		</tr>
		<tr>
			<th>{{ 'admin.biography.Nationality'|trans }}</th>
			<td>{% if entity.country is not empty %}{{ entity.country.title }}{% endif %}</td>
		</tr>
		<tr>
			<th>{{ "admin.form.Language"|trans }}</th>
			<td>{{ entity.language.title }}</td>
		</tr>
		<tr>
			<th>Wikidata</th>
			<td>{{ entity.wikidata }}</td>
		</tr>
		<tr>
			<th>{{ "admin.form.Slug"|trans }}</th>
			<td>{{ entity.slug }}</td>
		</tr>
	</table>
	<hr>
	<a href="{{ path('app_biographyadmin_index') }}"><i class="fas fa-list"></i> {{ 'admin.index.List'|trans }}</a> - <a href="{{ path('app_biographyadmin_edit', { 'id' : entity.id }) }}"><i class="fas fa-edit"></i> {{ 'admin.index.Update'|trans }}</a> - <a href="{{ path('app_biographyadmin_new') }}"><i class="fas fa-plus-square"></i> {{ 'admin.index.Create'|trans }}</a>
{% endblock %}