src/Entity/Poem.php
<?php

namespace App\Entity;

use App\Service\GenericFunction;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PoemRepository")
 */
class Poem
{
	const FOLDER = "poem";
	const PATH_FILE = "photo/".self::FOLDER."/";

	const PUBLISHED_STATE = 0;
	const DRAFT_STATE = 1;
	const DELETE_STATE = 2;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $text;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $releasedDate;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $authorType;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $slug;
	
	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\PoeticForm")
     */
    protected $poeticForm;

	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\Biography")
     */
    protected $biography;

	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\Country")
     */
    protected $country;

	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\Source")
     */
    protected $collection;
	
	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    protected $user;

    /**
     * @ORM\Column(type="integer")
     */
    protected $state;
	
	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\FileManagement")
     */
    protected $fileManagement;

	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\Language")
     */
	protected $language;

    /**
     * @ORM\OneToMany(targetEntity=PoemImage::class, cascade={"persist", "remove"}, mappedBy="poem", orphanRemoval=true)
     */
    protected $images;

   /**
    * ORM\ManyToMany(targetEntity=Tag::class, inversedBy="poems", cascade={"persist"})
    */
	protected $tags;

    /**
     * @ORM\Column(type="string", length=500)
     */
    protected $identifier;

    public function __construct()
    {
        $this->images = new ArrayCollection();
		$this->state = self::PUBLISHED_STATE;
    }
	
	public function getSiteName(): String
	{
		return "Poéticus";
	}

	public function getStateString()
	{
		$res = "";
		
		switch($this->state)
		{
			case self::PUBLISHED_STATE:
				$res = "publication.state.Published";
				break;
			case self::DRAFT_STATE:
				$res = "publication.state.Draft";
				break;
			case self::DELETE_STATE:
				$res = "publication.state.Deleted";
				break;
			default:
				$res = "";
		}
		
		return $res;
	}

	public function getStateRealName()
	{
		$res = "";
		
		switch($this->state)
		{
			case self::PUBLISHED_STATE:
				$res = "published";
				break;
			case self::DRAFT_STATE:
				$res = "draft";
				break;
			case self::DELETE_STATE:
				$res = "deleted";
				break;
			default:
				$res = "";
		}
		
		return $res;
	}
	
	public function isBiography()
	{
		return $this->authorType == "biography";
	}

	public function isUser()
	{
		return $this->authorType == "user";
	}
	
	public function getAuthor()
	{
		if($this->isBiography())
			return $this->biography;
		else
			return $this->user;
	}
	
	public function getShowRoute(): String {
		return "app_indexpoeticus_read";
	}
	
	public function getAbstract(): String {
		return $this->title;
	}

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
		$this->setSlug();
    }

    public function getSlug()
    {
        return $this->slug;
    }

    public function setSlug()
    {
		if(empty($this->slug))
			$this->slug = GenericFunction::slugify($this->title);
    }

    public function getText()
    {
        return $this->text;
    }

    public function setText($text)
    {
        $this->text = $text;
    }

    public function getReleasedDate()
    {
        return $this->releasedDate;
    }

    public function setReleasedDate($releasedDate)
    {
        $this->releasedDate = $releasedDate;
    }

    public function getAuthorType()
    {
        return $this->authorType;
    }

    public function setAuthorType($authorType)
    {
        $this->authorType = $authorType;
    }

    public function getBiography()
    {
        return $this->biography;
    }

    public function setBiography($biography)
    {
        $this->biography = $biography;
    }

    public function getCountry()
    {
        return $this->country;
    }

    public function setCountry($country)
    {
        $this->country = $country;
    }

    public function getCollection()
    {
        return $this->collection;
    }

    public function setCollection($collection)
    {
        $this->collection = $collection;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser($user)
    {
        $this->user = $user;
    }

    public function getPoeticForm()
    {
        return $this->poeticForm;
    }

    public function setPoeticForm($poeticForm)
    {
        $this->poeticForm = $poeticForm;
    }

    public function getState()
    {
        return $this->state;
    }

    public function setState($state)
    {
        $this->state = $state;
    }

	public function getLanguage()
	{
		return $this->language;
	}
	
	public function setLanguage($language)
	{
		$this->language = $language;
	}

    public function getImages()
    {
        return $this->images;
    }
     
    public function addImage(PoemImage $image)
    {
        $this->images->add($image);
        $image->setPoem($this);
    }
	
    public function removeImage(PoemImage $image)
    {
        $image->setPoem(null);
        $this->images->removeElement($image);
    }
	
   /**
    * Add tags
    *
    * @param Tag $tags
    */
	public function addTag(Tag $tag)
	{
		$this->tags[] = $tag;
	}

    /**
     * Set tags
     *
     * @param string $tags
     */
    public function setTags($tags)
    {
        $this->tags = $tags;
    }

   /**
    * Remove tags
    *
    * @param Tag $tag
    */
	public function removeTag(Tag $tag)
	{
		$this->tags->removeElement($tag);
	}

	public function isTagExisted(Tag $tag)
	{
		foreach($this->tags as $t)
			if($tag->getId() == $t->getId())
				return true;
		
		return false;
	}

   /**
    * Get tags
    *
    * @return Doctrine\Common\Collections\Collection
    */
	public function getTags()
	{
		return $this->tags;
	}
	
	public function getFileManagement()
	{
		return $this->fileManagement;
	}
	
	public function setFileManagement($fileManagement)
	{
		$this->fileManagement = $fileManagement;
	}

	public function getIdentifier()
	{
		return $this->identifier;
	}
	
	public function setIdentifier($identifier)
	{
		$this->identifier = $identifier;
	}
}

src/Entity/Store.php
<?php

namespace App\Entity;

use App\Service\GenericFunction;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StoreRepository")
 */
class Store
{
	const FOLDER = "store";
	const PATH_FILE = "photo/".self::FOLDER."/";

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string")
     */
    protected $title;

	/**
	 * @ORM\Column(type="text", nullable=true)
	 */
	protected $text;
	
	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\Biography")
     */
    protected $biography;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $amazonCode;

	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\Language")
     */
	protected $language;

    /**
     * @ORM\Column(type="text")
     */
    protected $embedCode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $photo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $slug;

	/**
     * @ORM\ManyToOne(targetEntity="App\Entity\Source")
     */
    protected $source;

	private $partnerId = "activiparano-21";
	
	public function getExternalStoreLink()
	{
		return "http://www.amazon.fr/dp/".$this->amazonCode."/ref=nosim?tag=".$this->partnerId;
	}

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
		$this->setSlug();
    }

	public function getLanguage()
	{
		return $this->language;
	}
	
	public function setLanguage($language)
	{
		$this->language = $language;
	}

    /**
     * Set text
     *
     * @param text $text
     */
    public function setText($text)
    {
		$this->text = $text;
    }

    /**
     * Get text
     *
     * @return text 
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Set biography
     *
     * @param string $biography
     */
    public function setBiography($biography)
    {
        $this->biography = $biography;
    }

    /**
     * Get biography
     *
     * @return string 
     */
    public function getBiography()
    {
        return $this->biography;
    }

    /**
     * Set amazonCode
     *
     * @param integer $amazonCode
     */
    public function setAmazonCode($amazonCode)
    {
        $this->amazonCode = $amazonCode;
    }

    /**
     * Get amazonCode
     *
     * @return integer 
     */
    public function getAmazonCode()
    {
        return $this->amazonCode;
    }

    public function getPhoto()
    {
        return $this->photo;
    }

    public function setPhoto($photo)
    {
        $this->photo = $photo;
    }

    public function getEmbedCode()
    {
        return $this->embedCode;
    }

    public function setEmbedCode($embedCode)
    {
        $this->embedCode = $embedCode;
    }

    public function getSlug()
    {
        return $this->slug;
    }

    public function setSlug()
    {
		if(empty($this->slug))
			$this->slug = GenericFunction::slugify($this->title);
    }

    public function getSource()
    {
        return $this->source;
    }

    public function setSource($source)
    {
        $this->source = $source;
    }
}

templates/IndexQuotus/byauthor.html.twig
{% extends 'quotus_layout.html.twig' %}

{% block head_title %}{{ 'biography.index.ByAuthors'|trans }}{% endblock %}

{% block style_additional %}
	<link rel="stylesheet" type="text/css" href="{{ asset('js/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css') }}" media="screen" />
	<link rel="stylesheet" type="text/css" href="{{ asset('js/DataTables/Responsive-2.2.2/css/responsive.bootstrap.min.css') }}" media="screen" />
{% endblock %}
{% block script_additional %}
	<script src="{{ asset('js/DataTables/datatables.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/Responsive-2.2.2/js/dataTables.responsive.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/Responsive-2.2.2/js/responsive.bootstrap.min.js') }}"></script>

	<script type="text/javascript">
		$(function ()
		{
			$('table.index_directories').DataTable({
				"oLanguage": {
					"sUrl": "{{ asset('js/DataTables/language/dataTables.'~app.request.locale) }}.txt"
				}, 
				"bFilter": true,
				"bInfo": false,
				"bSort": true,
				"bLengthChange": true,
				"iDisplayLength": 15,
				"bProcessing": true,
				"bServerSide": true,
				"sAjaxSource": "{{ path('app_indexquotus_byauthorsdatatables') }}",
				"autoWidth": false
			});
		});
	</script>
{% endblock %}

{% block main_title %}{{ 'biography.index.ByAuthors'|trans }}{% endblock %}

{% block main_content %}
	<table class="index_directories table table-striped table-bordered dt-responsive">
		<thead>
			<th>{{ 'biography.table.Author'|trans }}</th>
			<th>{{ 'biography.table.Photo'|trans }}</th>
			<th class="phone">{{ 'biography.table.Number'|trans }}</th>
		</thead>
		<tbody>
		</tbody>
	</table>
{% endblock %}

templates/IndexQuotus/byfictionalcharacter.html.twig
{% extends 'quotus_layout.html.twig' %}

{% block head_title %}{{ 'fictionalCharacter.index.ByFictionalCharacters'|trans }}{% endblock %}

{% block style_additional %}
	<link rel="stylesheet" type="text/css" href="{{ asset('js/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css') }}" media="screen" />
	<link rel="stylesheet" type="text/css" href="{{ asset('js/DataTables/Responsive-2.2.2/css/responsive.bootstrap.min.css') }}" media="screen" />
{% endblock %}
{% block script_additional %}
	<script src="{{ asset('js/DataTables/datatables.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/Responsive-2.2.2/js/dataTables.responsive.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/Responsive-2.2.2/js/responsive.bootstrap.min.js') }}"></script>

	<script type="text/javascript">
		$(function ()
		{
			$('table.index_directories').DataTable({
				"oLanguage": {
					"sUrl": "{{ asset('js/DataTables/language/dataTables.'~app.request.locale) }}.txt"
				}, 
				"bFilter": true,
				"bInfo": false,
				"bSort": true,
				"bLengthChange": true,
				"iDisplayLength": 15,
				"bProcessing": true,
				"bServerSide": true,
				"sAjaxSource": "{{ path('app_indexquotus_byfictionalcharactersdatatables') }}",
				"autoWidth": false
			});
		});
	</script>
{% endblock %}

{% block main_title %}{{ 'fictionalCharacter.index.ByFictionalCharacters'|trans }}{% endblock %}

{% block main_content %}
	<table class="index_directories table table-striped table-bordered dt-responsive">
		<thead>
			<th>{{ 'fictionalCharacter.table.Character'|trans }}</th>
			<th>{{ 'fictionalCharacter.table.Photo'|trans }}</th>
			<th class="phone">{{ 'fictionalCharacter.table.Number'|trans }}</th>
		</thead>
		<tbody>
		</tbody>
	</table>
{% endblock %}

templates/IndexQuotus/bysource.html.twig
{% extends 'quotus_layout.html.twig' %}

{% block head_title %}{{ 'source.index.BySources'|trans }}{% endblock %}

{% block style_additional %}
	<link rel="stylesheet" type="text/css" href="{{ asset('js/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css') }}" media="screen" />
	<link rel="stylesheet" type="text/css" href="{{ asset('js/DataTables/Responsive-2.2.2/css/responsive.bootstrap.min.css') }}" media="screen" />
{% endblock %}
{% block script_additional %}
	<script src="{{ asset('js/DataTables/datatables.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/Responsive-2.2.2/js/dataTables.responsive.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/Responsive-2.2.2/js/responsive.bootstrap.min.js') }}"></script>
	
	<script type="text/javascript">
		$(function ()
		{
			$('table.index_directories').DataTable({
				{% if app.request.locale != 'en' %}
				"oLanguage": {
					"sUrl": "{{ asset('js/DataTables/language/dataTables.'~app.request.locale) }}.txt"
				},
				{% endif %}
				"bFilter": true,
				"bInfo": true,
				"bSort": true,
				"bLengthChange": true,
				"iDisplayLength": 15,
				"bProcessing": true,
				"bServerSide": true,
				"sAjaxSource": "{{ path('app_indexquotus_bysourcesdatatables') }}",
				"autoWidth": false
			});
		});
	</script>
{% endblock %}

{% block main_title %}{{ 'source.index.BySources'|trans }}{% endblock %}

{% block main_content %}
		<table class="index_directories table table-striped table-bordered dt-responsive">
		<thead>
			<th>{{ 'source.table.Title'|trans }}</th>
			<th>{{ 'source.table.Photo'|trans }}</th>
			<th class="phone">{{ 'source.table.Number'|trans }}</th>
		</thead>
		<tbody>
		</tbody>
	</table>
{% endblock %}

templates/IndexQuotus/generate_widget.html.twig
{% extends 'quotus_layout.html.twig' %}

{% block head_title %}Widget{% endblock %}

{% block script_additional %}
	<script src="{{ asset('js/clipboard.js/clipboard.min.js') }}"></script>
	<script type="text/javascript">
		$(function()
		{
			var clipboard = new ClipboardJS('.clip_button');

			clipboard.on('success', function(e) {
				$("#success_copy").addClass("alert alert-success");
				$("#success_copy span").text("{{ 'widget.random.TheCodeHasBeenCopiedSuccessfully'|trans }}");
				setTimeout(fade_out, 5000);
			});

			var fade_out = function() {
				$("#success_copy").removeClass("alert alert-success");
				$("#success_copy span").empty();
			}
		});
	</script>
{% endblock %}

{% block main_title %}{{ 'widget.random.IncorporateProverbsIntoYourWebsite'|trans }}{% endblock %}

{% block style_additional %}
{% endblock %}

{% block main_content %}
	<h3>{{ 'widget.random.AProverbAtRandom'|trans }}</h3>
	<div id="success_copy"><span></span></div>
	<textarea class="form-control" id="embedded_document" cols="65" rows="4"><iframe src="{{ url('widget', {'locale': app.request.locale}) }}" frameborder=0 style="width: 100%;" onload="this.style.height=this.contentDocument.body.scrollHeight +'px';"></iframe></textarea>
	<br>
	<button type="button" id="copy-button" class="btn btn-success vertical submitcomment clip_button" data-clipboard-action="copy"data-clipboard-target="#embedded_document" title="Click to copy me."><i class="fas fa-clipboard" aria-hidden="true"></i> {{ 'widget.random.Copy'|trans }}</button>

	<h4 class="mt-4">{{ 'widget.random.Preview'|trans }}</h4>
	<div>
	<iframe src="{{ url('widget') }}" frameborder=0 style="width: 100%;" onload="this.style.height=this.contentDocument.body.scrollHeight +'px';"></iframe>
	</div>
{% endblock %}

templates/IndexQuotus/last.html.twig
<ul>
	{% for entity in entities %}
		<li>
			<a href="{{ path('app_indexquotus_read', {'id' : entity.id, 'slug' : entity.slug}) }}" >{{ entity.text|striptags|raw }}</a>
			{% if entity.biography is not empty %}
				<br>
				<i class="fas fa-chevron-circle-right"></i> 
				<span class="font-weight-bold">{{ entity.biography.title }}</span>
			{% endif %}
		</li>
	{% endfor %}
</ul>

templates/IndexQuotus/source.html.twig
{% extends 'quotus_layout.html.twig' %}

{% block head_title %}{{ entity.title }}{% endblock %}

{% block style_additional %}
	<link rel="stylesheet" type="text/css" href="{{ asset('js/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css') }}" media="screen" />
	<link rel="stylesheet" type="text/css" href="{{ asset('js/DataTables/Responsive-2.2.2/css/responsive.bootstrap.min.css') }}" media="screen" />
{% endblock %}
{% block script_additional %}
	<script src="{{ asset('js/DataTables/datatables.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/Responsive-2.2.2/js/dataTables.responsive.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/DataTables/Responsive-2.2.2/js/responsive.bootstrap.min.js') }}"></script>
	
	<script type="text/javascript">
		$(function ()
		{
			oTable = $('table.index_directories').dataTable( {
				{% if app.request.locale != 'en' %}
				"oLanguage": {
					"sUrl": "{{ asset('js/DataTables/language/dataTables.'~app.request.locale) }}.txt"
				},
				{% endif %}
				"bFilter": true,
				"bInfo": true,
				"bSort": true,
				"bLengthChange": true,
				"iDisplayLength": 15,
				"bProcessing": true,
				"bServerSide": true,
				"sAjaxSource": "{{ path('app_indexquotus_sourcedatatables', {'sourceId' : entity.id }) }}",
				"autoWidth": false
			});
		});
	</script>
{% endblock %}

{% block main_title %}{{ entity.title }}{% endblock %}

{% block main_content %}
	{{ display_file(entity) }}
	<br>
	<p>{{ entity.text|raw }}</p>
	
	{% if entity.authors is not empty %}
		<hr>
		<h4>{{ 'source.index.Authors'|trans }}</h4>
		<table class="table table-bordered table-striped">
			<tbody>
			{% for au in entity.authors %}
				<tr>
					<th><a href="{{ path('app_indexquotus_author', {'id': au.id, 'slug': au.slug}) }}">{{ au.title }}</a></th>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	{% endif %}
	
	{% if entity.fictionalCharacters is not empty %}
		<hr>
		<h4>{{ 'source.index.Characters'|trans }}</h4>
		<table class="table table-bordered table-striped">
			<tbody>
			{% for fc in entity.fictionalCharacters %}
				<tr>
					<th><a href="{{ path('app_indexquotus_fictionalcharacter', {'id': fc.id, 'slug': fc.slug}) }}">{{ fc.title }}</a></th>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	{% endif %}
	<hr>
	<h4>{{ 'source.index.Quotes'|trans }}</h4>
	<table class="index_directories table table-striped table-bordered dt-responsive">
		<thead>
			<th>{{ 'source.table.Text'|trans }}</th>
			<th>{{ 'source.table.Author'|trans }}</th>
			<th class="phone">{{ 'source.table.Read'|trans }}</th>
		</thead>
		<tbody>
		</tbody>
	</table>
	
	{% if stores is not empty %}
	<hr>
	<h4>{{ 'store.index.Store'|trans }}</h4>
	<table class="index_author_store table table-striped table-bordered dt-responsive">
		<thead>
			<tr>
				<th>{{ 'store.author.Title'|trans }}</th>
				<th>{{ 'store.author.Action'|trans }}</th>
			</tr>
		</thead>
		<tbody>
			{% for store in stores %}
			<tr>
				<td>
					<p class="text-center font-weight-bold">{{ store.title }}</p>
					{% if store.photo is not empty %}<p class="text-center">{{ (constant('\\App\\Entity\\Store::PATH_FILE')~store.photo)|max_size_image() }}</p>{% else %}<div class="container-store-product center-iframe text-center">{{ store.embedCode|raw }}</div>{% endif %}
				</td>
				<td>
				    <a href="{{ path('app_index_readstore', {'id': store.id, 'slug': store.slug}) }}" class="btn btn-info"><i class="fas fa-plus" aria-hidden="true"></i></a>
				    <a href="{{ store.getExternalStoreLink() }}" rel="nofollow" class="btn btn-success" target="_blank"><i class="fas fa-shopping-basket" aria-hidden="true"></i></a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% endif %}
{% endblock %}

templates/IndexQuotus/stat.html.twig
<div class="flex-space-between">
	<span class="font-weight-bold">{{ "menu.left.NumberOfPublishedQuotes"|trans }}</span><span>{{ statistics }}</span>
</div>

templates/IndexQuotus/store.html.twig
{% extends 'quotus_layout.html.twig' %}

{% block head_title %}{{ 'store.index.Store'|trans }}{% endblock %}
{% block main_title %}{{ 'store.index.Store'|trans }}{% endblock %}

{% block meta_tag_description %}{% endblock %}

{% block main_content %}
	{% if pagination|length > 0 %}
		<form method="post" action="{{ path('app_indexquotus_store') }}" name="search_form">
		<div class="row">
			<div class="col-lg-6">
				<div class="input-group">
					<input type="text" class="form-control" name="query" value="{{ query }}" placeholder="{{ 'store.index.Search'|trans }} ...">
					<div class="input-group-append">
						<button class="btn btn-outline-secondary" type="submit"><i class="fas fa-search"></i></button>
					</div>
				</div>
			</div>
		</div>
		</form>
		<br>
	{% endif %}
	
	{% if pagination|length > 0 %}
	<div class="row mb-4">
		{% for entity in pagination %}
			<div class="col-sm-6 col-lg-4 py-2">
				<div class="card  h-100 mb-4">
					<div class="card-header">
						<h5><a href="{{ path('app_indexquotus_readstore', {'id': entity.id, 'slug': entity.slug}) }}">{{ entity.title }}</a></h5>
					</div>
					<div class="card-body">
						<div class="article_infos">
							<span><i class="fas fa-chevron-circle-right"></i> <span class="font-weight-bold">{% if entity.biography is not empty %}{{ entity.biography.title }}{% else %}{{ "store.index.UnknownAuthor"|trans }}{% endif %}</span></span><br>
						</div>
						<hr>
						<div class="center-iframe text-center">
							{{ entity.embedCode|raw }}
						</div>
					</div>
					<div class="card-footer text-muted">
						{% if entity.amazonCode %}
							<a href="{{ entity.externalStoreLink }}" rel="nofollow" class="float-left btn btn-dark" target="_blank"><span class="text-warning"><i class="fas fa-shopping-cart"></i> {{ "store.index.Buy"|trans }}</span></a>
						{% endif %}
						<span class="float-right btn"><a href="{{ path('app_indexquotus_readstore', {'id': entity.id, 'slug': entity.slug}) }}" class="text-info"><i class="fas fa-plus" aria-hidden="true"></i> {{ "store.index.MoreInformations"|trans }}</a></span>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	{% else %}
		<div class="alert alert-danger text-center">
			<i class="fas fa-exclamation-triangle" aria-hidden="true"></i> {{ 'store.index.NoProductFound'|trans }}
		</div>
	{% endif %}

	{% if pagination|length > 0 %}
		{{ knp_pagination_render(pagination) }}
	{% endif %}
{% endblock %}